name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  path:
    required: false
    description: |
      The directory to find the '.env' file. 
      Relative paths are resolved inside the workspace directory
    default: '.'
  quiet:
    required: false
    description: If true, don't print variables
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
