name: 'build-test'
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          path: .github/test-dir

      - name: Verify Export
        run: |
          if [[ "$TEST_EXPORT" != "foo" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi
          if [[ "$TEST_BASE" != "base" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi

  test-error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          if-file-not-found: warn

  test-quiet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          path: .github/test-dir
          # without log
          quiet: true

  test-multiple-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          path: .github/test-dir
          filenames:
            .env
            .env.test

      - name: Verify Export
        run: |
          if [[ "$TEST_EXPORT" != "foo_override" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi
          if [[ "$TEST_BASE" != "base" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi
