name: 'build-test'
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # `dist/index.js` is a special file in Actions.
  # When you reference an action with `uses:` in a workflow,
  # `index.js` is the code that will run.
  # For our project, we generate this file through a build process from other source files.
  # We need to make sure the checked-in `index.js` actually matches what we expect it to be.
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

  test-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          path: .github/test-dir

      - name: Verify Export
        run: |
          if [[ "$TEST_EXPORT" != "foo" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi
          if [[ "$TEST_BASE" != "base" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi

  test-error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          if-file-not-found: warn

  test-quiet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          path: .github/test-dir
          # without log
          quiet: true

  test-multiple-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          path: .github/test-dir
          filenames: |
            .env
            .env.test

      - name: Verify Export
        run: |
          if [[ "$TEST_EXPORT" != "foo_override" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi
          if [[ "$TEST_BASE" != "base" ]]; then
            echo Expected TEST_EXPORT set
            exit 1
          fi
